config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'map', to: 'pages#map', as: 'map'
  get :autocomplete, to: 'pages#autocomplete'

  resources :places

  # resources :reviews, except: [:new]
  resources :user_places, only: [:create]
  resources :user_experiences, only: [:create, :destroy]

  resources :cards

  resources :experiences, only: [:index, :show]

  resources :users, only: [:show, :edit, :update]

  resources :bookings do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :categories, only: [:index]

  get "/fetch_experiences" => 'experiences#from_category', as: 'fetch_experiences'

  get "/search" => 'pages#search'

  get "/redeem/:id" => 'cards#update'

  # Route to generate the QR code
  get "qrcode/generate" => "cards#generate", format: :svg
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cards
  has_many :bookings, dependent: :destroy
  has_many :user_experiences
  has_many :user_places
  has_many :user_interests

  mount_uploader :photo, PhotoUploader

  validates :email, presence: true, format: { with: /\A.*@.*\.*\z/ }
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_params, only: [:update]

  def show
    @user = current_user
    authorize @user
    @cards = Card.where(user_id: current_user.id).order('place_id DESC')
    authorize @cards
    @places = Place.all
    authorize @places
    @experiences = Experience.all
    authorize @experiences
    @user_places = UserPlace.where(user_id: current_user.id).order('place_id DESC')
    authorize @user_places
    @user_experiences = UserExperience.where(user_id: current_user.id).order('experience_id DESC')
    authorize @user_experiences
    @review = Review.new
    authorize @review

  end

  def edit
  end

  def update
    @user = User.find(current_user.id)
    authorize @user
    @user.update!(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :first_name, :last_name, :photo)
  end
end

app/views/users/_user_bookings.html.erb
<h4 class="mt-0 pt-0 text-center">My Bookings</h4>

<div class="mb-2">

  <% bookings_arr = bookings.sort {|a,b| b.id <=> a.id } %>

  <% bookings_arr.each do |booking| %>
  <!-- hide card after review -->
  <% hide_booking = booking.review.nil? ? "block" : "none" %>
  <div class="card" style="display: <%= hide_booking %>">
    <div class="card-body py-2">
      <div class="d-flex justify-content-between align-items-center">
        <div class="border-right pr-2 text-center">
          <p class="m-0 pr-2 day-num"><%= booking.date.strftime('%a') %></p>
          <p class="m-0 pr-2 day"><%= booking.date.strftime('%d') %></p>
          <p class="pr-2 month"><%= booking.date.strftime('%b') %></p>
        </div>
        <p class="text-center"><%= booking.experience.name %></p>

        <div>
          <p class="m-0">
            <%= link_to edit_booking_path(booking) do %>
            <i class="fas fa-edit"></i>
            <% end %>
          </p>
          <p>
            <%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } do %>
            <i class="fas fa-trash-alt"></i>
            <% end %>
          </p>
        </div>
      </div>
      <!-- Disable review button before the booking date -->
      <% if DateTime.now > booking.date %>
      <%= link_to 'Review', new_booking_review_path(booking), class: "d-block btn btn-sm btn-success mt-2" %>
      <% else %>
      <%= link_to 'Review', new_booking_review_path(booking), class: 'd-block btn btn-sm btn-success disabled mt-2' %>
      <% end %>
    </div>
  </div>
  <% end %>

</div>

app/views/users/_user_cards.html.erb
<div class="title">
  <h4 class="text-center mb-4">My Stamp Cards</h4>

  <% hide_cards = @cards.where(state: 1).empty? ? "none" : "block" %>

  <div style="display: <%= hide_cards %>">
    <h5>Your free coffee is waiting</h5>
    <h6>Redeem your card at the cafe</h6>
    <div class="scrolling-wrapper-flexbox">
      <% @cards.where(state: 1).each do |card| %>
          <div class="card ml-0" style="width: 17rem;">
            <%= cl_image_tag @places.find(card.place_id).photo, class: "card-img-top" %>
            <div class="card-body">
              <h3 class="mb-1"><%= @places.find(card.place_id).name %></h3>
              <p class="card-text">Your stamps:</p>
              <% card.stamp_count.times do %>
                <%= image_tag("stamp.jpg", style:"height: 25px; width:auto;") %>
              <% end %>
              <% if card.completed? %>
                <%= link_to card_path(card.id) do %>
                  <button class="btn btn-sm btn-primary">Redeem</button>
                <% end %>
              <% end %>
            </div>
          </div>
      <% end %>
    </div>
  </div>

  <hr>

  <h5>Your recent experiences</h5>
  <h6>You are only a few stamps away from a free coffee</h6>
  <div class="scrolling-wrapper-flexbox mb-5">
    <% @cards.where(state: 0).each do |card| %>

      <div class="card ml-0 mt-0" style="width: 17rem;">
        <%= cl_image_tag @places.find(card.place_id).photo, class: "card-img-top" %>
        <div class="card-body">
          <h3 class="mb-1"><%= @places.find(card.place_id).name %></h3>
          <p class="card-text">Your stamps:</p>
          <% card.stamp_count.times do %>
            <%= image_tag("stamp.jpg", style:"height: 25px; width:auto;") %>
          <% end %>
          <% if card.completed? %>
            <%= link_to card_path(card.id) do %>
              <button class="btn btn-sm btn-primary">Redeem</button>
            <% end %>
          <% end %>
        </div>
      </div>

    <% end %>
  </div>
</div>

app/views/users/_user_favs.html.erb
<div class="title">
  <h3>My Favorites</h3>

  <ul class="list-group">
  <% @user_places.each do |user_place| %>
    <li class="list-group-item">
      <%= link_to place_path(user_place.place_id), class: "" do %>
        <i class="fas fa-star"></i><%=@places.find(user_place.place_id).name %>
      <% end %>
    </li>
    <% end %>
    <% @user_experiences.each do |user_experience| %>
      <li class="list-group-item">
        <%= link_to experience_path(user_experience.experience_id), class: "" do %>
          <i class="fas fa-star"></i><%=@experiences.find(user_experience.experience_id).name %>
        <% end %>
      </li>
      <% end %>
  </ul>
</div>

app/views/users/_user_profile.html.erb
<div class="title">
  <h4 class="text-center">My Profile</h4>
  <%= simple_form_for @user, validate: true do |f| %>
  <%= f.input :email %>
  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>


  <%= f.submit class: "btn btn-primary" %>
  <% end %>
  <%= link_to destroy_user_session_path, method: :delete, class: 'btn btn-danger' do %>
  <i></i> Log Out Now!
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Users#edit</h1>
<p>Find me in app/views/users/edit.html.erb</p>

app/views/users/show.html.erb
  <div class="top">
    <div class="user-profile">
      <% if @user.photo.nil? %>
        <img src="https://kitt.lewagon.com/placeholder/users/papillard">
      <% else %>
        <%= cl_image_tag(@user.photo) %>
      <% end %>
      <div class="user-details">
        <h3>Hi <%= @user.first_name %>!</h3>
      </div>
    </div>
  </div>
  <div class="filter-btn">
    <a id="all" href="#"><i class="fas fa-user"></i></a>
    <a id="one" href="#"><i class="fas fa-heart"></i></a>
    <a id="two" href="#"><i class="fas fa-calendar"></i></a>
    <a id="three" href="#"><i class="fas fa-stamp"></i></a>
    <span class="toggle-btn ion-android-funnel fas fa-bars"></span>
  </div>
  <div class="bottom">

    <div id="favs" class="menus" style="display:none">
      <%= render partial: 'user_favs', locals: { places: @user.user_places, experiences: @user.user_experiences} %>
    </div>

    <div id="bookings" class="menus pb-3 mb-3" style="display:block;">
      <%= render partial: 'user_bookings', locals: { bookings: @user.bookings} %>
    </div>

    <div id="cards" class="menus" style="display:none">
      <%= render partial: 'user_cards', locals: { cards: @user.cards} %>
    </div>

    <div id="profile" class="menus" style="display:none">
      <%= render partial: 'user_profile', method: :patch, locals: { users: @user} %>
    </div>

  </div>

app/views/users/show.js.erb
// function refreshList() {
//   const newMenu = document.getElementById('menu');
//   newMenu.innerHTML = '';
// }

// function displayFilteredList(menuContent) {
//   const menu = document.getElementById('menu');
//   menu.insertAdjacentHTML('beforeend', menuContent);
// }

// $('#all').click(function() {

//   $('ul.tasks li').slideDown(300);

// });

// $('#one').click(function() {
//   $('.tasks li:not(.one)').slideUp(300, function() {
//     $('.one').slideDown(300);

//   });
// });


// $('#two').click(function() {
//   console.log('yay');
//   refreshList();
//   displayFilteredList('<%= j render: "user_bookings" %>');
// });

// $('#three').click(function() {
//   $('.tasks li:not(.three)').slideUp(300, function() {
//     $('.three').slideDown(300);

//   });
// });

app/views/users/update.html.erb
<h1>Users#update</h1>
<p>Find me in app/views/users/update.html.erb</p>