config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'map', to: 'pages#map', as: 'map'
  get :autocomplete, to: 'pages#autocomplete'

  resources :places

  # resources :reviews, except: [:new]
  resources :user_places, only: [:create]
  resources :user_experiences, only: [:create, :destroy]

  resources :cards

  resources :experiences, only: [:index, :show]

  resources :users, only: [:show, :edit, :update]

  resources :bookings do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :categories, only: [:index]

  get "/fetch_experiences" => 'experiences#from_category', as: 'fetch_experiences'

  get "/search" => 'pages#search'

  get "/redeem/:id" => 'cards#update'

  # Route to generate the QR code
  get "qrcode/generate" => "cards#generate", format: :svg
end

app/views/shared/_bottom_navigation.html.erb
<nav class="navbar botnav fixed-bottom navbar-dark text-justify">
  <%= link_to root_path, class: "nav-link active" do %>
    <i class="fas fa-home"></i>
  <% end %>
  <%= link_to map_path, class: "nav-link" do %>
    <i class="fas fa-search"></i>
  <% end %>
  <% if user_signed_in? %>
    <%= link_to user_path(current_user), class: "nav-link" do %>
    <i class="fas fa-user"></i>
    <% end %>
  <% else %>
    <%= link_to new_user_session_path, class: "nav-link" do %>
      <i class="fas fa-user"></i>
    <% end %>
  <% end %>
<!--   <%= link_to map_path, class: "nav-link" do %>
    <i class="fas fa-map"></i>
  <% end %> -->
</nav>

app/views/shared/_card_form.html.erb
<%= simple_form_for @card, validate: true do |f| %>
  <%= f.input :place_id %>

  <div class="d-flex justify-content-between">
    <%= f.submit class: 'btn btn-primary mb-2' %>
    <%= link_to 'Cancel', new_card_path, class: 'btn btn-outline-secondary mb-2' %>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">

  <%= link_to do %>
  <div class="justify-content-center align-items-center d-flex">
      <p>COFFEEISSEUR</p>
      <p><%= image_tag 'logo.png' %></p>
  </div>
  <% end  %>

  <% if false %>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
  <% end %>
</div>

app/views/shared/_place_form.html.erb
<%= simple_form_for @place, validate: true do |f| %>
  <%= f.input :name %>
  <%= f.input :street %>
  <%= f.input :city %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>

  <div class="d-flex justify-content-between">
    <%= f.submit class: 'btn btn-primary mb-2' %>
    <%= link_to 'Cancel', places_path, class: 'btn btn-outline-secondary mb-2' %>
  </div>
<% end %>

app/views/shared/_test.html.erb
_test.html.erb
<h1>pickel</h1>