config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'map', to: 'pages#map', as: 'map'
  get :autocomplete, to: 'pages#autocomplete'

  resources :places

  # resources :reviews, except: [:new]
  resources :user_places, only: [:create]
  resources :user_experiences, only: [:create, :destroy]

  resources :cards

  resources :experiences, only: [:index, :show]

  resources :users, only: [:show, :edit, :update]

  resources :bookings do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :categories, only: [:index]

  get "/fetch_experiences" => 'experiences#from_category', as: 'fetch_experiences'

  get "/search" => 'pages#search'

  get "/redeem/:id" => 'cards#update'

  # Route to generate the QR code
  get "qrcode/generate" => "cards#generate", format: :svg
end

app/views/pages/home.html.erb
<!-- <div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80);">
  <div class="container">
    <h1>What would you like to experience?</h1>
  </div>
</div> -->

<div class="home-video-wrapper align-items-center justify-content-center">
  <h1 class="home">What would you like to experience today?</h1>

  <div class="gradient align-self-start"></div>
  <%= video_tag "coffee_video.mp4", autoplay: true, loop: true, mute: true, playsinline: true, autobuffer: true, class: "home_video" %>
</div>



<!-- Experiences -->

<div class="container mb-5 pt-0">

  <div class="d-flex justify-content-between align-items-center">
    <h5>Explore Experiences</h5>
    <%= link_to "See all", experiences_path, class: 'link-home'%>
  </div>

  <div id="card-slider" class="scrolling-wrapper-flexbox">
    <% @experiences.each do |experience| %>

    <div class="card ml-0 mt-0" style="width: 16rem;">
      <%= link_to experience_path(experience) do %>
        <%=
        cl_image_tag experience.photo, class: "card-img-top" %>
      <% end %>
      <div class="card-body px-3 py-2">
        <p class="card-text"><%= experience.name %></p>
        <div class="d-flex justify-content-between mb-0">
          <p class="mb-1"><%= experience.average_rating.floor(1) %> <i class="fas fa-coffee"></i></p>
          <p class="mb-1"><i class="fas fa-map-marker-alt"></i> <%= experience.place.city %></p>
        </div>
      </div>

    </div>
    <% end %>
  </div>
</div>

app/views/pages/map.html.erb
  <%= form_tag search_path, method: :get  do %>
    <div id = "search-data" class="form-search  search-data d-flex justify-content-between" data-places ="<%= [].to_json%>">
      <%= text_field_tag :query,
        params[:query],
        autocomplete: :off,
        class: "form-control search-input",
        placeholder: "🔍 Search",
        value: "Lisbon"
      %>
    </div>
  <% end %>

<div
  id="map"
  style="width: 100%;
  height: 100vh;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
></div>

app/views/pages/search.html.erb
<!-- <div class="container" id="searchcontainer"> -->
  <%= form_tag search_path, method: :get  do %>
    <div id = "search-data" class="form-search  search-data d-flex justify-content-between" data-places ="<%= [].to_json%>">
      <%= text_field_tag :query,
        params[:query],
        autocomplete: :off,
        class: "form-control search-input",
        placeholder: "🔍 Search"
         submit_tag "Search", class: "btn btn-success" do %>
        <i class="fas fa-play"></i>
      <% end %>
    </div>
  <% end %>

  <div class="results">
    <ul class="list-group list-group-flush">
      <% @places.each do |place| %>
        <li class="list-group-item">
          <div class="d-flex justify-content-between">
            <div>
            <%= link_to place.name, place_path(place.id) %><br>
            <i class="fas fa-map-marker-alt"></i>  <%= link_to place.address, place_path(place.id), class: "city" %>
            </div>
            <div>
            <%= cl_image_tag place.photo, class: "img-result" %>
            </div>
          </div>
        </li>
        <% end %>
      </ul>
  </div>
<!-- </div> -->