config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'map', to: 'pages#map', as: 'map'
  get :autocomplete, to: 'pages#autocomplete'

  resources :places

  # resources :reviews, except: [:new]
  resources :user_places, only: [:create]
  resources :user_experiences, only: [:create, :destroy]

  resources :cards

  resources :experiences, only: [:index, :show]

  resources :users, only: [:show, :edit, :update]

  resources :bookings do
    resources :reviews, only: [:index, :new, :create]
  end

  resources :categories, only: [:index]

  get "/fetch_experiences" => 'experiences#from_category', as: 'fetch_experiences'

  get "/search" => 'pages#search'

  get "/redeem/:id" => 'cards#update'

  # Route to generate the QR code
  get "qrcode/generate" => "cards#generate", format: :svg
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :category
  belongs_to :place
  has_many :bookings
  has_many :user_experiences
  has_many :reviews, through: :bookings

  mount_uploader :photo, PhotoUploader

  validates :name, presence: true
  validates :description, presence: true
  validates :photo, presence: true
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_experience, only: [:show]

  def index
    if params[:category_id].present?
      @experiences = policy_scope(Experience.where(category_id: params[:category_id]))
    else
      @experiences = policy_scope(Experience)
    end
    @categories = Category.all
  end

  def show
    authorize @experience
    @booking = Booking.new

    @user_experiences = UserExperience.where(experience_id: @experience.id)

    @compliments = @experience.reviews.all.group(:compliment).count
    @compliments_sum = @experience.reviews.all.size

  end

  private

  def set_experience
    @experience = Experience.find(params[:id])
  end
end

app/views/experiences/_experience_list.html.erb
<div id="experience_list">
  <% experiences.each do |experience| %>

  <div id="carouselExperience" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">

        <div class="card" style="width: 18rem;">
          <%= link_to experience_path(experience) do %>
          <%= cl_image_tag experience.photo, class: "card-img-top" %>
          <% end %>
          <div class="card-body px-3 py-2">
            <p class="card-text"><%= experience.name %></p>
            <div class="d-flex justify-content-between mb-0">
              <p class="mb-1"><%= experience.average_rating.round(1) %> <i class="fas fa-coffee"></i></p>
              <p class="mb-1"><i class="fas fa-map-marker-alt"></i> <%= experience.place.city %></p>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
  <hr>

  <% end %>
</div>

app/views/experiences/index.html.erb
<div class="scrolling-wrapper-flexbox">
    <% @categories.each do |category| %>

      <%= link_to experiences_path(category_id: category.id), remote: true do %>
        <div class="icon-container text-center">
          <div class="card-avatar"><i class="<%= category.icon %>"></i></div>
          <figcaption class="figure-caption text-center text-nowrap mt-1"><%= category.name %></figcaption>
        </div>
      <% end %>

  <% end %>
</div>

<div class="container mb-5 mt-0 pt-0">
  <%= render partial: 'experience_list', locals: { experiences: @experiences} %>
</div>

app/views/experiences/index.js.erb
function refreshList() {
  const newExperienceList = document.getElementById('experience_list');
  newExperienceList.innerHTML = '';
}

function displayFilteredList(experienceHTML) {
  const experiencesList = document.getElementById('experience_list');
  experiencesList.insertAdjacentHTML('beforeend', experienceHTML);
}

refreshList();
displayFilteredList('<%= j render "experience_list", experiences: @experiences %>');

app/views/experiences/show.html.erb
<%= cl_image_tag @experience.photo, class: "card-img-top" %>

<div class="container">

  <h4 class="experience text-center"><%= @experience.name %></h4>
  <p class="location text-muted"><i class="fas fa-map-marker-alt mr-1"></i><%= @experience.place.name %></p>

  <p class="text-center"><%= @experience.description %></p>

  <div class= "text-center pb-3">
    <% if @user_experiences.empty? %>
      <%= link_to user_experiences_path(experience_id: @experience.id), method: :post, class: 'btn btn-sm btn-outline-success' do %>
        <i class="fas fa-heart"></i> Save
      <% end %>
    <% else %>

      <%= link_to user_experience_path(experience_id: @experience.id), method: :delete, class: 'btn btn-sm btn-outline-success active' do %>
        <i class="fas fa-heart"></i> Saved
      <% end %>
    <% end %>
    <%= link_to new_booking_path, {'data-toggle' =>  "modal", 'data-target' => "#bookingModalCenter-#{@experience.id}", class: 'btn btn-sm btn-outline-success'} do %>
      <i class="fas fa-plus"></i> Book Now
    <% end %>
  </div>






    <div class="comp-bar mt-3 py-2">
      <h6>Coffeeisseurs Love</h6>

      <% @compliments.each do |compliment| %>
        <p>
          <% case compliment[0].name %>
          <% when 'Food' %>
            <i class="fas fa-utensils"></i>
          <% when 'Space' %>
            <i class="fas fa-couch"></i>
          <% when 'Coffee' %>
            <i class="fas fa-mug-hot"></i>
          <% when 'Staff' %>
            <i class="far fa-user"></i>
          <% when 'Customers' %>
            <i class="fas fa-user-friends"></i>
          <% else %>
          <% end %>
          <%= compliment[0].name %>
        </p>
        <div class="progress my-2">
          <% comp_precentage = (compliment[1].to_f / @compliments_sum.to_f) * 100 %>
          <div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: <%= comp_precentage %>%;" aria-valuenow="<%= comp_precentage %>" aria-valuemin="0" aria-valuemax="100"></div>
        </div>
      <% end %>
    </div>

  <!-- Reviews -->
  <h6 class="pt-2 mt-3 mb-0">Popular Reviews</h6>
  <small class="text-muted my-0"><%= @experience.reviews.count %> reviews</small>
  <div class="scrolling-wrapper-flexbox my-2">
      <% @experience.reviews.each do |review| %>

        <div class="card ml-0 mt-0" style="width: 16rem;">
          <div class="card-body px-3 py-2">
            <div class="d-flex justify-content-between">
              <h5>
                <% review.rating.times do %>
                  <i class="fas fa-coffee"></i>
                <% end %>
              </h5>
              <small><%= time_ago_in_words(review.created_at) %></small>
            </div>
            <!-- compliments begin -->
            <div class="d-flex justify-content-right my-1">
                <span class="badge badge-pill badge-success">
                <% case review.compliment.name %>
                <% when 'Food' %>
                  <i class="fas fa-utensils"></i>
                <% when 'Space' %>
                  <i class="fas fa-couch"></i>
                <% when 'Coffee' %>
                  <i class="fas fa-mug-hot"></i>
                <% when 'Staff' %>
                  <i class="far fa-user"></i>
                <% when 'Customers' %>
                  <i class="fas fa-user-friends"></i>
                <% else %>
                <% end %>
                  <%= review.compliment.name %>
              </span>
            </div>
            <!-- compliments end -->
            <div id="card-collapse" class="collapse-content">
              <p class="card-text collapse" id="collapseContent"><%= review.content %></p>
              <a class="p-1 my-1 mr-0 collapsed" data-toggle="collapse" href="#collapseContent" aria-expanded="false" aria-controls="collapseContent"></a>
            </div>
          </div>
        </div>

      <% end %>
  </div>

</div>


<!-- Booking modal -->

<div class="modal fade" id="bookingModalCenter-<%= @experience.id %>" tabindex="-1" role="dialog" aria-labelledby="bookingModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="bookingModalLongTitle"><%= @experience.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">

        <%= simple_form_for @booking, validate: true do |f| %>
        <%= f.input :date, as: :string, input_html: { class: 'flatpickr-input'} %>
        <%= f.input :experience_id, as: :hidden, :input_html => { value: @experience.id } %>
        <div class="d-flex justify-content-between">
          <%= f.submit class: 'btn btn-primary' %>
          <%= f.button :button, 'Cancel', :type => 'reset', class: "btn btn-outline-secondary", data: { dismiss: "modal", target: "bookingModalCenter-#{@experience.id}" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<!-- End of Booking modal -->